import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import { I_USER } from "../../types";
import UserService from "./service";
export interface UsersState {
  data: I_USER[];
  loading: boolean;
  error?: any | null;
}

const initialState: UsersState = {
  data: [],
  loading: false,
  error: null,
};

// The function below is called a thunk and allows us to perform async logic. It
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchAllUsers = createAsyncThunk(
  "users/fetchAllUsers",

  async (_, { rejectWithValue }) => {
    try {
      const response = await UserService.getAllUsers();
      return response;
    } catch (err) {
      return rejectWithValue(err);
    }
  }
);

export const usersSlice = createSlice({
  name: "users",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    deleteUser: (state, action) => {
      const { id } = action.payload;
      const updatedUsers = state.data.filter((user) => user.id !== id);
      state.data = updatedUsers;
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
    },
    addNewUser: (state, action) => {
      const generateID = state.data.length
        ? Math.max(...state.data.map((item) => item.id)) + 1
        : 1;
      const { city, ...otherUserProps } = action.payload;
      state.data = [
        {
          id: generateID,
          address: {
            city,
          },
          ...otherUserProps,
        },
        ...state.data,
      ];
    },
    editUser: (state, action) => {
      const { id } = action.payload;
      const userIndex = state.data.findIndex((user) => user.id === id);
      const { city, ...otherUserProps } = action.payload;
      if (userIndex > -1) {
        let userFound = state.data[userIndex];
        state.data[userIndex] = {
          ...userFound,
          address: { ...userFound.address, city },
          ...otherUserProps,
        };
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(fetchAllUsers.pending, (state, action) => {
      state.data = [];
      state.loading = true;
    });
    builder.addCase(fetchAllUsers.fulfilled, (state, action) => {
      state.data = action.payload;
      state.loading = false;
    });

    builder.addCase(fetchAllUsers.rejected, (state, action) => {
      state.data = [];
      state.loading = false;
      state.error = action.error;
    });
  },
});

export const { deleteUser, addNewUser, editUser } = usersSlice.actions;

export const selectUsers = (state: RootState) => state.users;

export default usersSlice.reducer;
